package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/cpuguy83/go-md2man/v2/md2man"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/plytz/caramelo/internal/place"
)

func init() {
	register(func(a *app) *cobra.Command { return a.manualCmd() })
}

type manualFlag struct {
	Name      string `json:"name"`
	Shorthand string `json:"shorthand,omitempty"`
	Type      string `json:"type"`
	Default   string `json:"default,omitempty"`
	Usage     string `json:"usage"`
}

type manualCommand struct {
	Path        string          `json:"path"`
	Usage       string          `json:"usage"`
	Short       string          `json:"short"`
	Long        string          `json:"long,omitempty"`
	Holds       string          `json:"holds,omitempty"`
	Example     string          `json:"example,omitempty"`
	Flags       []manualFlag    `json:"flags,omitempty"`
	Subcommands []manualCommand `json:"subcommands,omitempty"`
}

type manual struct {
	Name        string          `json:"name"`
	Short       string          `json:"short"`
	Description string          `json:"description"`
	Role        string          `json:"role"`
	Context     *place.Context  `json:"context,omitempty"`
	Agents      []string        `json:"agents"`
	ExitCodes   map[string]int  `json:"exit_codes"`
	Environment []manualFlag    `json:"environment"`
	GlobalFlags []manualFlag    `json:"global_flags"`
	Commands    []manualCommand `json:"commands"`

	where []string
	note  string
}

var manualAgentNotes = []string{
	"Every command accepts --json. A command that returns a result then prints exactly one JSON document on standard output and nothing else; events and logs print one JSON object per line; run, test and env exec give standard output to the command they run.",
	"Progress and diagnostics go to standard error. With --progress json each line on standard error is one JSON event with the same shape as `caramelo events --json`.",
	"Exit codes are stable: 0 is success, 1 is a failure the command reports, 2 is a usage error (unknown command, bad flag, missing argument, or a command typed on a machine it does not belong on).",
	"No command needs a terminal. Anything a person is asked interactively can be answered with a flag, and when standard input is not a terminal the command fails at once naming that flag instead of waiting.",
	"The fleet a command talks to is picked by --fleet (CARAMELO_FLEET is its default), then a local caramelod socket if there is one, then the fleet recorded for the app of this checkout, then commander.default_fleet, then the only fleet there is; with several fleets and none of those, the command refuses and names them. --machine user@host reaches a box that is in no fleet yet: typed on the command line it drops whatever CARAMELO_FLEET said, as --fleet drops CARAMELO_MACHINE, and asking for both at once is refused.",
	"The app and the environment default to the git checkout the command runs in; --app and --env (or CARAMELO_APP and CARAMELO_ENV) name them explicitly.",
	"Every command holds only where it makes sense: on a commander, on a hub, on a member, on a box with no config at all, or as root. A command typed where it does not hold is refused before it runs, exit 2, in one line naming where it belongs; `caramelo context` says where you are. A session the daemon runs for a command forwarded to another machine is never refused this way. A command that holds here but is not on this machine's approved list yet is dormant: it is left out the same way and refused with exit 2 in one line naming CARAMELO_EXPERIMENTAL, which runs it anyway, and `caramelo manual --role all` still lists it.",
	"--help is scoped to the place it is typed in: it opens with the same line `caramelo context` opens with, lists only the commands that hold there, leaves out a group no child of which holds, and says after the list how many commands are hidden. The help of a single command prints wherever it is typed, whether or not it holds there.",
	"This manual is scoped the same way and generated by the binary that prints it, so there is no copy of it to go stale: `caramelo manual` is the manual of the machine it runs on, `caramelo manual --role commander|hub|member` renders one role against a canonical machine of that role, and `caramelo manual --role all` is every command of every role. Each command's section says where it holds.",
	"Names in the manual are placeholders: feat-x is an environment, shop is an app, home is a fleet, laptop is a commander, box is a hub and worker is a member.",
}

var manualEnvironment = []manualFlag{
	{Name: "CARAMELO_FLEET", Type: "string", Usage: "the fleet to talk to, as --fleet"},
	{Name: "CARAMELO_MACHINE", Type: "string", Usage: "a raw ssh target to talk to, as --machine"},
	{Name: "CARAMELO_APP", Type: "string", Usage: "the app, as --app on the commands that take one"},
	{Name: "CARAMELO_ENV", Type: "string", Usage: "the environment, as --env on the commands that take one"},
	{Name: "CARAMELO_SSH", Type: "string", Usage: "the ssh program used to reach a user@host machine (default: ssh)"},
	{Name: "CARAMELO_SSH_OPTS", Type: "string", Usage: "extra arguments for that ssh, split like shell words"},
	{Name: "CARAMELO_DEBUG", Type: "string", Usage: "when set, say on standard error which transport was chosen and why"},
	{Name: "CARAMELO_EXPERIMENTAL", Type: "string", Usage: "when set, commands that are not on this machine's approved list run instead of being refused"},
	{Name: "CARAMELO_CONFIG_DIR", Type: "path", Usage: "directory holding a machine's config.yaml, as --config-dir (default: /etc/caramelo)"},
	{Name: "XDG_CONFIG_HOME", Type: "path", Usage: "absolute path under which the commander config, its keys and its tunnel records live, in caramelo/ (default: ~/.config on every platform)"},
	{Name: "XDG_CACHE_HOME", Type: "path", Usage: "absolute path under which ssh control sockets live, in caramelo/ (default: ~/.cache on every platform)"},
	{Name: "XDG_RUNTIME_DIR", Type: "path", Usage: "where the transparent-mode service's control socket lives, in caramelo/ (default: the cache dir)"},
	{Name: "SUDO_USER", Type: "string", Usage: "set by sudo: on a machine that has no config.yaml of its own, the commander config and cache read are that user's, not root's"},
}

const manualRoleAll = "all"

const manualEveryRole = "every command of every role: a box with no config at all, " +
	"a commander, a hub and a member"

func manualRoles() []string {
	return []string{place.RoleCommander, place.RoleHub, place.RoleMember, manualRoleAll}
}

type manualScope struct {
	role   string
	ctx    place.Context
	every  bool
	here   bool
	hidden int
}

func (s *manualScope) holds(cmd *cobra.Command) bool {
	if s.every {
		return true
	}
	if shownHere(cmd, s.ctx) {
		return true
	}
	s.hidden++
	return false
}

func (s *manualScope) where() []string {
	if s.every {
		return []string{manualEveryRole}
	}
	return s.ctx.HeaderParts()
}

func (s *manualScope) note() string {
	switch {
	case s.every:
		return "Every command of every role is here and each section says where its command holds; " +
			"'caramelo manual' is the manual of the machine you are on."
	case !s.here:
		return fmt.Sprintf("This is the manual of a canonical %s, not of this machine; "+
			"'caramelo manual' is the manual of where you are.", s.role)
	case s.hidden > 0:
		return hiddenHere(s.hidden)
	}
	return ""
}

func everyRoleScope() *manualScope { return &manualScope{role: manualRoleAll, every: true} }

func manualScopeOfRole(role string) (*manualScope, error) {
	if role == manualRoleAll {
		return everyRoleScope(), nil
	}
	for _, name := range manualRoles() {
		if name != role {
			continue
		}
		c, ok := place.Canonical(role)
		if !ok {
			return nil, fmt.Errorf("render the manual of a %s: no canonical machine of that role", role)
		}
		return &manualScope{role: role, ctx: c}, nil
	}
	return nil, &usageError{fmt.Errorf("--role is one of %s, not %q",
		strings.Join(manualRoles(), ", "), role)}
}

func (a *app) manualScope(cmd *cobra.Command, role string) (*manualScope, error) {
	if name := strings.TrimSpace(role); name != "" {
		return manualScopeOfRole(name)
	}
	c, err := a.place(cmd.Context())
	if err != nil {
		return everyRoleScope(), nil
	}
	return &manualScope{role: c.Role, ctx: c, here: true}, nil
}

func (a *app) manualCmd() *cobra.Command {
	var markdown, man bool
	var role string
	cmd := &cobra.Command{
		Use:   "manual",
		Short: "The manual of this machine: every command that holds here, with examples",
		Long: `manual renders a command tree as one document: what each command does, its
flags with their defaults, where it holds and examples. The text is generated
from the same definitions the commands run on, so it cannot drift from the
binary, and nothing ships a copy of it.

By default it is the manual of this machine. It opens with the line 'caramelo
context' opens with, lists the commands that hold where it runs, and says how
many it left out. --role commander, hub or member renders that role against a
canonical machine of that role, for reading about a place you are not standing
in, and --role all is every command of every role.

Plain text laid out like a manual page is the default, for reading in a
terminal (pipe it to less). --markdown prints the Markdown source, the form an
agent reads. --man prints a roff manual page: pipe it to man, or install it as
caramelo.1. With --json the manual is a structured tree of commands and flags,
with the role and the place it was rendered for.`,
		Example: `  caramelo manual | less                     # the commands of this machine
  caramelo manual --role all | less          # every command of every role
  caramelo manual --role hub                 # what a hub does, from a laptop
  caramelo manual --markdown                 # the Markdown an agent reads
  caramelo manual --man | man -l -
  caramelo manual --json | jq '.commands[] | select(.path == "caramelo deploy")'`,
		Args: exactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			if markdown && man {
				return &usageError{fmt.Errorf("--markdown and --man are opposites; pick one")}
			}
			s, err := a.manualScope(cmd, role)
			if err != nil {
				return err
			}
			m := buildManual(cmd.Root(), s)
			return a.printer().Result(m, func(w io.Writer) error {
				var err error
				switch {
				case man:
					_, err = w.Write(md2man.Render([]byte(renderManual(m, true))))
				case markdown:
					_, err = io.WriteString(w, renderManual(m, false))
				default:
					_, err = io.WriteString(w, renderPlain(m))
				}
				return err
			})
		},
	}
	cmd.Flags().StringVar(&role, "role", "",
		"the role to render instead of this machine: commander, hub, member, or all")
	cmd.Flags().BoolVar(&markdown, "markdown", false, "print the Markdown source instead of plain text")
	cmd.Flags().BoolVar(&man, "man", false, "print a roff manual page instead of plain text")
	return available(cmd, always)
}

func buildManual(root *cobra.Command, s *manualScope) manual {
	m := manual{
		Name:        root.Name(),
		Short:       root.Short,
		Description: strings.TrimSpace(root.Long),
		Role:        s.role,
		Agents:      manualAgentNotes,
		ExitCodes:   map[string]int{"ok": ExitOK, "error": ExitError, "usage": ExitUsage},
		Environment: manualEnvironment,
		GlobalFlags: manualFlags(root.PersistentFlags()),
	}
	for _, c := range manualChildren(root) {
		if mc, ok := buildManualCommand(c, s); ok {
			m.Commands = append(m.Commands, mc)
		}
	}
	if !s.every {
		here := s.ctx
		m.Context = &here
	}
	m.where, m.note = s.where(), s.note()
	return m
}

func manualChildren(cmd *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, c := range cmd.Commands() {
		if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

func buildManualCommand(cmd *cobra.Command, s *manualScope) (manualCommand, bool) {
	mc := manualCommand{
		Path:    cmd.CommandPath(),
		Usage:   cmd.UseLine(),
		Short:   cmd.Short,
		Long:    strings.TrimSpace(cmd.Long),
		Example: strings.TrimSpace(dedent(strings.TrimRight(cmd.Example, "\n"))),
		Flags:   manualFlags(cmd.NonInheritedFlags()),
	}
	if w, ok := whenOf(cmd); ok {
		mc.Holds = w.text
	}
	if !cmd.HasSubCommands() {
		return mc, s.holds(cmd)
	}
	for _, c := range manualChildren(cmd) {
		if sub, ok := buildManualCommand(c, s); ok {
			mc.Subcommands = append(mc.Subcommands, sub)
		}
	}
	return mc, len(mc.Subcommands) > 0
}

func manualFlags(fs *pflag.FlagSet) []manualFlag {
	var out []manualFlag
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		def := f.DefValue
		if def == "false" || def == "[]" || def == "0s" {
			def = ""
		}
		out = append(out, manualFlag{Name: f.Name, Shorthand: f.Shorthand, Type: f.Value.Type(), Default: def, Usage: f.Usage})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func renderManual(m manual, forMan bool) string {
	var b strings.Builder
	if forMan {
		fmt.Fprintf(&b, "# %s 1 \"\" \"%s\" \"%s manual\"\n\n", strings.ToUpper(m.Name), m.Name, m.Name)
		fmt.Fprintf(&b, "# NAME\n\n%s - %s\n\n", m.Name, m.Short)
		fmt.Fprintf(&b, "# SYNOPSIS\n\n**%s** [command] [flags]\n\n", m.Name)
		fmt.Fprintf(&b, "# DESCRIPTION\n\n%s%s\n\n", markdownWhere(m), m.Description)
	} else {
		fmt.Fprintf(&b, "# %s manual\n\n%s%s\n\n", m.Name, markdownWhere(m), m.Description)
	}

	fmt.Fprintf(&b, "%s\n\n", manualHeading(forMan, 1, "For agents"))
	for _, n := range m.Agents {
		fmt.Fprintf(&b, "- %s\n", n)
	}
	fmt.Fprintf(&b, "\n%s\n\n", manualHeading(forMan, 1, "Exit codes"))
	fmt.Fprintf(&b, "| Code | Meaning |\n|---|---|\n| %d | success |\n| %d | the command failed and said why on standard error |\n| %d | usage error: unknown command, bad flag or missing argument |\n\n",
		m.ExitCodes["ok"], m.ExitCodes["error"], m.ExitCodes["usage"])

	fmt.Fprintf(&b, "%s\n\n", manualHeading(forMan, 1, "Environment"))
	fmt.Fprintf(&b, "| Variable | Description |\n|---|---|\n")
	for _, e := range m.Environment {
		fmt.Fprintf(&b, "| `%s` | %s |\n", e.Name, manualCell(e.Usage))
	}
	fmt.Fprintf(&b, "\n%s\n\n", manualHeading(forMan, 1, "Global flags"))
	fmt.Fprintf(&b, "Every command accepts these.\n\n")
	writeFlagTable(&b, m.GlobalFlags)

	fmt.Fprintf(&b, "\n%s\n\n", manualHeading(forMan, 1, "Commands"))
	for _, c := range m.Commands {
		writeIndex(&b, c, 0)
	}
	b.WriteString("\n")
	for _, c := range m.Commands {
		writeCommand(&b, c, forMan)
	}
	return b.String()
}

func markdownWhere(m manual) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", strings.Join(m.where, " · "))
	if m.note != "" {
		fmt.Fprintf(&b, "%s\n\n", m.note)
	}
	return b.String()
}

func writeIndex(b *strings.Builder, c manualCommand, depth int) {
	fmt.Fprintf(b, "%s- `%s`: %s\n", strings.Repeat("  ", depth), c.Path, c.Short)
	for _, s := range c.Subcommands {
		writeIndex(b, s, depth+1)
	}
}

func writeCommand(b *strings.Builder, c manualCommand, forMan bool) {
	fmt.Fprintf(b, "%s\n\n", manualHeading(forMan, 1, c.Path))
	fmt.Fprintf(b, "%s\n\n", c.Short)
	fmt.Fprintf(b, "```\n%s\n```\n\n", c.Usage)
	if c.Holds != "" {
		fmt.Fprintf(b, "%s\n\n", holdsOnLine(c.Holds))
	}
	if c.Long != "" {
		fmt.Fprintf(b, "%s\n\n", c.Long)
	}
	if c.Example != "" {
		fmt.Fprintf(b, "%s\n\n```sh\n%s\n```\n\n", manualHeading(forMan, 2, "Examples"), c.Example)
	}
	if len(c.Flags) > 0 {
		fmt.Fprintf(b, "%s\n\n", manualHeading(forMan, 2, "Flags"))
		writeFlagTable(b, c.Flags)
		b.WriteString("\n")
	}
	if len(c.Subcommands) > 0 {
		fmt.Fprintf(b, "%s\n\n", manualHeading(forMan, 2, "Subcommands"))
		for _, s := range c.Subcommands {
			fmt.Fprintf(b, "- `%s`: %s\n", s.Path, s.Short)
		}
		b.WriteString("\n")
	}
	for _, s := range c.Subcommands {
		writeCommand(b, s, forMan)
	}
}

func holdsOnLine(holds string) string { return "Holds on " + holds + "." }

func writeFlagTable(b *strings.Builder, flags []manualFlag) {
	fmt.Fprintf(b, "| Flag | Type | Default | Description |\n|---|---|---|---|\n")
	for _, f := range flags {
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		def := ""
		if f.Default != "" {
			def = "`" + f.Default + "`"
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", name, f.Type, def, manualCell(f.Usage))
	}
}

func manualHeading(forMan bool, level int, text string) string {
	if forMan {
		if level == 1 {
			return "# " + strings.ToUpper(text)
		}
		return "## " + text
	}
	return strings.Repeat("#", level+1) + " " + text
}

func manualCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.ReplaceAll(s, "\n", " ")
}

func dedent(s string) string {
	lines := strings.Split(s, "\n")
	indent := -1
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		n := len(l) - len(strings.TrimLeft(l, " \t"))
		if indent < 0 || n < indent {
			indent = n
		}
	}
	if indent <= 0 {
		return s
	}
	for i, l := range lines {
		if len(l) >= indent {
			lines[i] = l[indent:]
		}
	}
	return strings.Join(lines, "\n")
}

func renderPlain(m manual) string {
	var b strings.Builder
	writePlainWhere(&b, m)
	title := strings.ToUpper(m.Name) + "(1)"
	fmt.Fprintf(&b, "%s%s%s\n\n", title, strings.Repeat(" ", max(1, 78-2*len(title)-len(m.Name+" manual"))), m.Name+" manual")
	fmt.Fprintf(&b, "NAME\n    %s - %s\n\n", m.Name, m.Short)
	fmt.Fprintf(&b, "SYNOPSIS\n    %s [command] [flags]\n\n", m.Name)
	fmt.Fprintf(&b, "DESCRIPTION\n%s\n", indent(m.Description, 4))
	b.WriteString("FOR AGENTS\n")
	for _, n := range m.Agents {
		b.WriteString(indent(hang(wrap(n, 72), "- ", "  "), 4))
	}
	b.WriteString("\nEXIT CODES\n")
	fmt.Fprintf(&b, "    %d    success\n    %d    the command failed and said why on standard error\n    %d    usage error: unknown command, bad flag or missing argument\n\n",
		m.ExitCodes["ok"], m.ExitCodes["error"], m.ExitCodes["usage"])
	b.WriteString("ENVIRONMENT\n")
	for _, e := range m.Environment {
		fmt.Fprintf(&b, "    %s\n%s", e.Name, indent(wrap(e.Usage, 70), 8))
	}
	b.WriteString("\nGLOBAL FLAGS\n    Every command accepts these.\n\n")
	writePlainFlags(&b, m.GlobalFlags, 4)
	b.WriteString("\nCOMMANDS\n")
	for _, c := range m.Commands {
		writePlainIndex(&b, c, 4)
	}
	b.WriteString("\n")
	for _, c := range m.Commands {
		writePlainCommand(&b, c)
	}
	return b.String()
}

func writePlainWhere(b *strings.Builder, m manual) {
	for _, line := range headerLines(m.where) {
		fmt.Fprintln(b, line)
	}
	if m.note != "" {
		fmt.Fprintln(b, wrap(m.note, 78))
	}
	fmt.Fprintln(b)
}

func writePlainIndex(b *strings.Builder, c manualCommand, depth int) {
	fmt.Fprintf(b, "%s%-*s%s\n", strings.Repeat(" ", depth), max(1, 34-depth), c.Path, c.Short)
	for _, s := range c.Subcommands {
		writePlainIndex(b, s, depth+2)
	}
}

func writePlainCommand(b *strings.Builder, c manualCommand) {
	fmt.Fprintf(b, "%s\n", strings.ToUpper(c.Path))
	fmt.Fprintf(b, "    %s\n\n", c.Short)
	fmt.Fprintf(b, "    Usage: %s\n\n", c.Usage)
	if c.Holds != "" {
		fmt.Fprintf(b, "%s\n", indent(wrap(holdsOnLine(c.Holds), 74), 4))
	}
	if c.Long != "" {
		fmt.Fprintf(b, "%s\n", indent(c.Long, 4))
	}
	if c.Example != "" {
		fmt.Fprintf(b, "    Examples:\n%s\n", indent(c.Example, 8))
	}
	if len(c.Flags) > 0 {
		b.WriteString("    Flags:\n")
		writePlainFlags(b, c.Flags, 8)
		b.WriteString("\n")
	}
	if len(c.Subcommands) > 0 {
		b.WriteString("    Subcommands:\n")
		for _, s := range c.Subcommands {
			fmt.Fprintf(b, "        %-30s%s\n", s.Path, s.Short)
		}
		b.WriteString("\n")
	}
	for _, s := range c.Subcommands {
		writePlainCommand(b, s)
	}
}

func writePlainFlags(b *strings.Builder, flags []manualFlag, depth int) {
	pad := strings.Repeat(" ", depth)
	for _, f := range flags {
		head := "--" + f.Name
		if f.Shorthand != "" {
			head = "-" + f.Shorthand + ", " + head
		}
		if f.Type != "bool" {
			head += " " + f.Type
		}
		if f.Default != "" {
			head += " (default " + f.Default + ")"
		}
		fmt.Fprintf(b, "%s%s\n%s", pad, head, indent(wrap(f.Usage, 78-depth-4), depth+4))
	}
}

func indent(s string, n int) string {
	pad := strings.Repeat(" ", n)
	var b strings.Builder
	for _, l := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		if strings.TrimSpace(l) == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString(pad + l + "\n")
	}
	return b.String()
}

func wrap(s string, width int) string {
	words := strings.Fields(s)
	var b strings.Builder
	line := 0
	for i, w := range words {
		if line > 0 && line+1+len(w) > width {
			b.WriteString("\n")
			line = 0
		} else if i > 0 {
			b.WriteString(" ")
			line++
		}
		b.WriteString(w)
		line += len(w)
	}
	return b.String()
}

func hang(s, first, rest string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		if i == 0 {
			lines[i] = first + l
		} else {
			lines[i] = rest + l
		}
	}
	return strings.Join(lines, "\n")
}
