package vpnclient

import (
	"errors"
	"fmt"
	"strings"

	"github.com/plytz/caramelo/internal/vpn"
)

func WGQuick(rec Record, private string) (string, error) {
	if !rec.Valid() {
		return "", errors.New("the commander has not joined that machine yet; run 'caramelo vpn up'")
	}
	private, err := KeyBase64(private)
	if err != nil {
		return "", fmt.Errorf("the commander's private key: %w", err)
	}
	machineKey, err := KeyBase64(rec.MachineKey)
	if err != nil {
		return "", fmt.Errorf("the public key of %s: %w", rec.Machine, err)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# caramelo: peer %q on the network of %s\n", rec.PeerName, rec.Machine)
	fmt.Fprintf(&b, "# Generated by 'caramelo vpn config'. It holds the commander's private key.\n")
	fmt.Fprintf(&b, "# Names under .%s resolve at %s inside the tunnel.\n\n", vpn.Domain, rec.Resolver())
	b.WriteString("[Interface]\n")
	fmt.Fprintf(&b, "PrivateKey = %s\n", private)
	fmt.Fprintf(&b, "Address = %s/32\n", rec.IP)
	fmt.Fprintf(&b, "DNS = %s, %s\n", rec.MachineIP, vpn.Domain)
	fmt.Fprintf(&b, "MTU = %d\n\n", vpn.MTU)
	b.WriteString("[Peer]\n")
	fmt.Fprintf(&b, "PublicKey = %s\n", machineKey)
	fmt.Fprintf(&b, "Endpoint = %s\n", rec.Endpoint)

	fmt.Fprintf(&b, "AllowedIPs = %s\n", rec.Subnet)

	fmt.Fprintf(&b, "PersistentKeepalive = %d\n", keepalive)
	return b.String(), nil
}
