package release

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/plytz/caramelo/internal/config"
	"github.com/plytz/caramelo/internal/stack"
)

const WorkDir = "/app"

const GeneratedBy = "# Generated by caramelo"

var imageRefRe = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,254}$`)

type Dockerfile struct {
	App     string
	Service string

	Stack string

	Tree string

	Version string

	Image string

	Manifests stack.Manifest

	Install string
	Build   string
	Run     string
}

func (d Dockerfile) Render() (string, error) {
	if err := d.validate(); err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "%s %s for service %q of %s (%s stack), release %s.\n",
		GeneratedBy, version(d.Version), d.Service, appName(d.App), stackName(d.Stack), ShortTree(d.Tree))
	b.WriteString("# The export of the commit it was written into is thrown away after the build.\n")
	switch {
	case d.Manifests.NeedsSource:
		b.WriteString("#\n")
		b.WriteString("# The install needs the project itself, not only its manifests, so the tree\n")
		b.WriteString("# is copied first and the install is not cached across commits.\n")
	case !d.Manifests.Empty():
		b.WriteString("#\n")
		b.WriteString("# The dependency manifests are copied before the install, so a commit that\n")
		b.WriteString("# did not touch them reuses this layer.\n")
	}
	fmt.Fprintf(&b, "FROM %s\n", d.Image)
	fmt.Fprintf(&b, "WORKDIR %s\n", WorkDir)

	sourceFirst := d.Manifests.NeedsSource || d.Manifests.Empty()
	if !sourceFirst {
		fmt.Fprintf(&b, "COPY %s ./\n", strings.Join(d.Manifests.Files, " "))
		if line := runLine(d.Install); line != "" {
			b.WriteString(line + "\n")
		}
		b.WriteString("COPY . .\n")
	} else {
		b.WriteString("COPY . .\n")
		if line := runLine(d.Install); line != "" {
			b.WriteString(line + "\n")
		}
	}
	if line := runLine(d.Build); line != "" {
		b.WriteString(line + "\n")
	}
	cmd, err := argv("sh", "-c", d.Run)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "CMD %s\n", cmd)
	return b.String(), nil
}

func (d Dockerfile) validate() error {
	where := fmt.Sprintf("service %q", d.Service)
	if d.Service == "" {
		where = "a service"
	}
	switch {
	case d.Image == "":
		return fmt.Errorf("generate a Dockerfile for %s: no image: stack detection found no toolchain, "+
			"so %s must say `image:` or bring a Dockerfile", where, config.FileName)
	case !imageRefRe.MatchString(d.Image):
		return fmt.Errorf("generate a Dockerfile for %s: %q is not a usable image reference", where, d.Image)
	case strings.TrimSpace(d.Run) == "":
		return fmt.Errorf("generate a Dockerfile for %s: no command: give it a `run:` in %s, "+
			"or a Dockerfile so it can be built and run from its own image", where, config.FileName)
	}
	for _, f := range d.Manifests.Files {
		if f == "" || strings.ContainsAny(f, " \t\n\r\"\\") || strings.HasPrefix(f, "-") {
			return fmt.Errorf("generate a Dockerfile for %s: %q cannot be copied", where, f)
		}
	}
	return nil
}

func runLine(cmd string) string {
	trimmed := strings.TrimSpace(cmd)
	if trimmed == "" {
		return ""
	}
	if strings.ContainsAny(trimmed, "\n\r") || strings.HasSuffix(trimmed, `\`) {

		s, err := argv("sh", "-c", cmd)
		if err != nil {
			return "RUN " + strings.ReplaceAll(trimmed, "\n", " ")
		}
		return "RUN " + s
	}
	return "RUN " + trimmed
}

func argv(parts ...string) (string, error) {
	b, err := json.Marshal(parts)
	if err != nil {
		return "", fmt.Errorf("render %v: %w", parts, err)
	}
	return string(b), nil
}

func version(v string) string {
	if strings.TrimSpace(v) == "" {
		return "(unknown version)"
	}
	return v
}

func appName(app string) string {
	if app == "" {
		return "an app"
	}
	return app
}

func stackName(s string) string {
	if s == "" {
		return "undetected"
	}
	return s
}
