# Generated by caramelo 0.7.0 for service "web" of shop (go stack), release a1b2c3d4e5f6.
# The export of the commit it was written into is thrown away after the build.
#
# The dependency manifests are copied before the install, so a commit that
# did not touch them reuses this layer.
FROM golang:1.23
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
CMD ["sh","-c","go run ."]
