# Generated by caramelo 0.7.0 for service "web" of shop (undetected stack), release a1b2c3d4e5f6.
# The export of the commit it was written into is thrown away after the build.
FROM alpine:3.20
WORKDIR /app
COPY . .
CMD ["sh","-c","./server --port $PORT"]
