# Generated by caramelo 0.7.0 for service "web" of shop (python stack), release a1b2c3d4e5f6.
# The export of the commit it was written into is thrown away after the build.
#
# The install needs the project itself, not only its manifests, so the tree
# is copied first and the install is not cached across commits.
FROM python:3.12
WORKDIR /app
COPY . .
RUN pip install -e .
CMD ["sh","-c","gunicorn shop:app"]
