# Generated by caramelo 0.7.0 for service "web" of shop (python stack), release a1b2c3d4e5f6.
# The export of the commit it was written into is thrown away after the build.
#
# The dependency manifests are copied before the install, so a commit that
# did not touch them reuses this layer.
FROM python:3.12
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .
CMD ["sh","-c","python manage.py runserver 0.0.0.0:$PORT"]
