# Generated by caramelo 0.7.0 for service "web" of shop (rails stack), release a1b2c3d4e5f6.
# The export of the commit it was written into is thrown away after the build.
#
# The dependency manifests are copied before the install, so a commit that
# did not touch them reuses this layer.
FROM ruby:3.3
WORKDIR /app
COPY Gemfile Gemfile.lock .ruby-version ./
RUN bundle install
COPY . .
CMD ["sh","-c","bin/rails server -b 0.0.0.0 -p $PORT"]
